sections:
  traking:
    display: Tracking
    fields:
      tracking_id:
        type: text
        validate: required
        width: 100
      performance_section:
        type: section
      async:
        type: toggle
        width: 50
      beacon:
        type: toggle
        width: 50
      tracking_features_section:
        type: section
      anonymize_ip:
        type: toggle
        width: 50
      display_features:
        type: toggle
        width: 50
      link_id:
        type: toggle
        width: 50
      user_tracking_options_section:
        type: section
      track_uid:
        type: toggle
        width: 50
      ignore_admins:
        type: toggle
        width: 50
  debug:
    display: Debuging
    fields:
      debug:
        type: toggle
        width: 33
      trace_debugging:
        type: toggle
        width: 33
      disable_sending:
        type: toggle
        width: 33
  reporting:
    display: Reporting
    fields:
      view_id:
        type: text
        width: 50
      cache_lifetime_in_minutes:
        type: integer
        width: 50
      cache_location:
        type: text
        width: 100
      service_account_credentials_json:
        type: text
        width: 100
      roles_with_access:
        type: list
        width: 100
