routes:
  /: home
  /blog/tags: blog/taxonomies
  '/users/{username}': user/profile
  /account: user/account
  /login: auth/login
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
collections:
  grape:
    en: '/grape/{slug}'
    fr: '/grape/{slug}'
    nl: '/grape/{slug}'
  wines:
    en: '/wines/{slug}'
    fr: '/wines/{slug}'
    nl: '/wines/{slug}'
  estate:
    en: '/estate/{slug}'
    fr: '/estate/{slug}'
    nl: '/estate/{slug}'
  region:
    en: '/region/{slug}'
    fr: '/region/{slug}'
    nl: '/region/{slug}'
