routes:
  /: home
  '/users/{username}': user/profile
  /account: user/account
  /login: auth/login
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /wines/style/{taxonomy}:
    layout: api
    template: wines
  /!/Fetch/collection/wines:
    layout: api
    template: wine/pairing_results
    content_type: json
  /winesmap.xml:
    template: winesmap
    layout: winesmap
    content_type: xml
  /sitemap:
    template: sitemap
    layout: sitemap
    content_type: xml
collections:
  grape:
    en: '/grape/{slug}'
    fr: '/grape/{slug}'
    nl: '/grape/{slug}'
  wines:
    en: '/wines/{slug}'
    fr: '/wines/{slug}'
    nl: '/wines/{slug}'
  estate:
    en: '/estate/{slug}'
    fr: '/estate/{slug}'
    nl: '/estate/{slug}'
  region:
    en: '/region/{slug}'
    fr: '/region/{slug}'
    nl: '/region/{slug}'
taxonomies: '{  }'
